version: "3"

networks:
  mynetwork:
    name: mynetwork

volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - mynetwork
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABSE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 3333:8080
    depends_on:
      - postgres
    networks:
      - mynetwork
  app_1:
    image: nginx
    networks:
      - mynetwork
  app_2:
    image: nginx
    networks:
      - mynetwork
  nginx:
    build:
      context: .nginx/
    ports:
      - 3002:3002
      - 4090:4090
    networks:
      - mynetwork
    volumes:
      - .nginx/nginx.conf:/etc/nginx/conf.d/default.conf